<?php 

$ml = filter_input(INPUT_POST, 'ml',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$mma = filter_input(INPUT_POST, 'mma',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$mmi = filter_input(INPUT_POST, 'mmi',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$mj = filter_input(INPUT_POST, 'mj',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$mv = filter_input(INPUT_POST, 'mv',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$ms = filter_input(INPUT_POST, 'ms',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$md = filter_input(INPUT_POST, 'md',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);

$tl = filter_input(INPUT_POST, 'tl',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$tm = filter_input(INPUT_POST, 'tm',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$tmi = filter_input(INPUT_POST, 'tmi',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$tj = filter_input(INPUT_POST, 'tj',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$tv = filter_input(INPUT_POST, 'tv',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$ts = filter_input(INPUT_POST, 'ts',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$td = filter_input(INPUT_POST, 'td',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);

$nl = filter_input(INPUT_POST, 'nl',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$nm = filter_input(INPUT_POST, 'nm',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$nmi = filter_input(INPUT_POST, 'nmi',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$nj = filter_input(INPUT_POST, 'nj',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$nv = filter_input(INPUT_POST, 'nv',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$ns = filter_input(INPUT_POST, 'ns',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
$nd = filter_input(INPUT_POST, 'nd',FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);





/*if ($nd) {
	echo "verdadero";
}else{
	echo "falso";
}*/




?>